import 'package:supabase_flutter/supabase_flutter.dart';
import './supabase_service.dart';

/// CNA Automation & Smart Assistant Engine Service
/// Handles event detection, workflow execution, notifications, reminders, tasks
class AutomationService {
  static AutomationService? _instance;
  static AutomationService get instance => _instance ??= AutomationService._();
  AutomationService._();

  SupabaseClient get _client => SupabaseService.client;
  String? get _userId => _client.auth.currentUser?.id;

  // ─── EVENT DETECTION SERVICE ─────────────────────────────────────────────

  Future<void> publishEvent({
    required String eventType,
    required String entityType,
    String? entityId,
    Map<String, dynamic> payload = const {},
  }) async {
    final userId = _userId;
    if (userId == null) return;
    try {
      await _client.from('automation_events').insert({
        'event_type': eventType,
        'entity_type': entityType,
        'entity_id': entityId,
        'user_id': userId,
        'payload': payload,
        'processed': false,
      });
    } catch (_) {}
  }

  Future<List<Map<String, dynamic>>> getUnprocessedEvents() async {
    final userId = _userId;
    if (userId == null) return _demoEvents();
    try {
      final result = await _client
          .from('automation_events')
          .select()
          .eq('user_id', userId)
          .eq('processed', false)
          .order('created_at', ascending: false)
          .limit(50);
      return List<Map<String, dynamic>>.from(result);
    } catch (_) {
      return _demoEvents();
    }
  }

  Future<void> markEventProcessed(String eventId) async {
    try {
      await _client
          .from('automation_events')
          .update({'processed': true})
          .eq('id', eventId);
    } catch (_) {}
  }

  // ─── WORKFLOW ENGINE ──────────────────────────────────────────────────────

  Future<Map<String, dynamic>> createWorkflow({
    required String name,
    required String triggerType,
    Map<String, dynamic> condition = const {},
    Map<String, dynamic> action = const {},
  }) async {
    final userId = _userId;
    if (userId == null) return {};
    try {
      final result = await _client
          .from('automation_rules')
          .insert({
            'user_id': userId,
            'name': name,
            'trigger_type': triggerType,
            'condition': condition,
            'action': action,
            'enabled': true,
          })
          .select()
          .single();
      await _logWorkflow(
        workflowId: result['id'],
        status: 'created',
        result: {'name': name},
      );
      return result;
    } catch (_) {
      return {};
    }
  }

  Future<List<Map<String, dynamic>>> getWorkflows() async {
    final userId = _userId;
    if (userId == null) return _demoWorkflows();
    try {
      final result = await _client
          .from('automation_rules')
          .select()
          .eq('user_id', userId)
          .order('created_at', ascending: false);
      return List<Map<String, dynamic>>.from(result);
    } catch (_) {
      return _demoWorkflows();
    }
  }

  Future<void> toggleWorkflow(String workflowId, bool enabled) async {
    try {
      await _client
          .from('automation_rules')
          .update({'enabled': enabled})
          .eq('id', workflowId);
    } catch (_) {}
  }

  Future<void> deleteWorkflow(String workflowId) async {
    try {
      await _client.from('automation_rules').delete().eq('id', workflowId);
    } catch (_) {}
  }

  Future<Map<String, dynamic>> runWorkflow(String workflowId) async {
    try {
      final workflow = await _client
          .from('automation_rules')
          .select()
          .eq('id', workflowId)
          .single();
      final action = workflow['action'] as Map<String, dynamic>? ?? {};
      final results = <String, dynamic>{};

      if (action['notify_user'] == true) {
        await createNotification(
          title: 'Workflow Executed: ${workflow['name']}',
          message: 'Automation rule triggered successfully.',
          notificationType: 'automation',
          priority: 'normal',
        );
        results['notification_sent'] = true;
      }
      if (action['create_task'] == true) {
        await createTask(
          title: 'Action Required: ${workflow['name']}',
          description:
              'This task was auto-generated by workflow: ${workflow['name']}',
          taskType: 'automation',
          priority: 'high',
        );
        results['task_created'] = true;
      }

      await _logWorkflow(
        workflowId: workflowId,
        status: 'completed',
        result: results,
      );
      return results;
    } catch (_) {
      return {};
    }
  }

  Future<void> _logWorkflow({
    required String workflowId,
    required String status,
    Map<String, dynamic> result = const {},
  }) async {
    final userId = _userId;
    if (userId == null) return;
    try {
      await _client.from('workflow_logs').insert({
        'workflow_id': workflowId,
        'user_id': userId,
        'status': status,
        'execution_time': DateTime.now().toIso8601String(),
        'result': result,
      });
    } catch (_) {}
  }

  Future<List<Map<String, dynamic>>> getWorkflowLogs() async {
    final userId = _userId;
    if (userId == null) return _demoWorkflowLogs();
    try {
      final result = await _client
          .from('workflow_logs')
          .select()
          .eq('user_id', userId)
          .order('execution_time', ascending: false)
          .limit(20);
      return List<Map<String, dynamic>>.from(result);
    } catch (_) {
      return _demoWorkflowLogs();
    }
  }

  // ─── NOTIFICATION SERVICE ─────────────────────────────────────────────────

  Future<void> createNotification({
    required String title,
    required String message,
    String notificationType = 'general',
    String priority = 'normal',
  }) async {
    final userId = _userId;
    if (userId == null) return;
    try {
      await _client.from('notifications').insert({
        'user_id': userId,
        'title': title,
        'message': message,
        'notification_type': notificationType,
        'priority': priority,
        'status': 'unread',
      });
    } catch (_) {}
  }

  Future<List<Map<String, dynamic>>> getNotifications({
    String? filterType,
    String? filterStatus,
  }) async {
    final userId = _userId;
    if (userId == null) return _demoNotifications();
    try {
      var query = _client.from('notifications').select().eq('user_id', userId);
      if (filterType != null && filterType != 'all') {
        query = query.eq('notification_type', filterType);
      }
      if (filterStatus != null && filterStatus != 'all') {
        query = query.eq('status', filterStatus);
      }
      final result = await query
          .order('created_at', ascending: false)
          .limit(100);
      return List<Map<String, dynamic>>.from(result);
    } catch (_) {
      return _demoNotifications();
    }
  }

  Future<int> getUnreadCount() async {
    final userId = _userId;
    if (userId == null) return 4;
    try {
      final result = await _client
          .from('notifications')
          .select('id')
          .eq('user_id', userId)
          .eq('status', 'unread');
      return (result as List).length;
    } catch (_) {
      return 4;
    }
  }

  Future<void> markNotificationRead(String notificationId) async {
    try {
      await _client
          .from('notifications')
          .update({
            'status': 'read',
            'read_at': DateTime.now().toIso8601String(),
          })
          .eq('id', notificationId);
    } catch (_) {}
  }

  Future<void> markAllNotificationsRead() async {
    final userId = _userId;
    if (userId == null) return;
    try {
      await _client
          .from('notifications')
          .update({
            'status': 'read',
            'read_at': DateTime.now().toIso8601String(),
          })
          .eq('user_id', userId)
          .eq('status', 'unread');
    } catch (_) {}
  }

  Future<void> deleteNotification(String notificationId) async {
    try {
      await _client.from('notifications').delete().eq('id', notificationId);
    } catch (_) {}
  }

  // ─── REMINDER SERVICE ─────────────────────────────────────────────────────

  Future<Map<String, dynamic>> createReminder({
    required String title,
    String? description,
    DateTime? dueDate,
    String repeatPattern = 'none',
  }) async {
    final userId = _userId;
    if (userId == null) return {};
    try {
      final result = await _client
          .from('reminders')
          .insert({
            'user_id': userId,
            'title': title,
            'description': description,
            'due_date': dueDate?.toIso8601String(),
            'repeat_pattern': repeatPattern,
            'completed': false,
          })
          .select()
          .single();
      return result;
    } catch (_) {
      return {};
    }
  }

  Future<List<Map<String, dynamic>>> getReminders({
    bool includeCompleted = false,
  }) async {
    final userId = _userId;
    if (userId == null) return _demoReminders();
    try {
      var query = _client.from('reminders').select().eq('user_id', userId);
      if (!includeCompleted) {
        query = query.eq('completed', false);
      }
      final result = await query.order('due_date', ascending: true);
      return List<Map<String, dynamic>>.from(result);
    } catch (_) {
      return _demoReminders();
    }
  }

  Future<void> completeReminder(String reminderId) async {
    try {
      await _client
          .from('reminders')
          .update({'completed': true})
          .eq('id', reminderId);
    } catch (_) {}
  }

  Future<void> deleteReminder(String reminderId) async {
    try {
      await _client.from('reminders').delete().eq('id', reminderId);
    } catch (_) {}
  }

  // ─── TASK MANAGER ─────────────────────────────────────────────────────────

  Future<Map<String, dynamic>> createTask({
    required String title,
    String? description,
    String taskType = 'general',
    String priority = 'medium',
    DateTime? dueDate,
  }) async {
    final userId = _userId;
    if (userId == null) return {};
    try {
      final result = await _client
          .from('tasks')
          .insert({
            'user_id': userId,
            'title': title,
            'description': description,
            'task_type': taskType,
            'priority': priority,
            'status': 'pending',
            'due_date': dueDate?.toIso8601String(),
          })
          .select()
          .single();
      return result;
    } catch (_) {
      return {};
    }
  }

  Future<List<Map<String, dynamic>>> getTasks({String? statusFilter}) async {
    final userId = _userId;
    if (userId == null) return _demoTasks();
    try {
      var query = _client.from('tasks').select().eq('user_id', userId);
      if (statusFilter != null && statusFilter != 'all') {
        query = query.eq('status', statusFilter);
      }
      final result = await query.order('due_date', ascending: true);
      return List<Map<String, dynamic>>.from(result);
    } catch (_) {
      return _demoTasks();
    }
  }

  Future<void> completeTask(String taskId) async {
    try {
      await _client
          .from('tasks')
          .update({'status': 'completed'})
          .eq('id', taskId);
    } catch (_) {}
  }

  Future<void> updateTaskStatus(String taskId, String status) async {
    try {
      await _client.from('tasks').update({'status': status}).eq('id', taskId);
    } catch (_) {}
  }

  Future<void> deleteTask(String taskId) async {
    try {
      await _client.from('tasks').delete().eq('id', taskId);
    } catch (_) {}
  }

  // ─── AI SMART ASSISTANT ───────────────────────────────────────────────────

  List<Map<String, dynamic>> getProactiveRecommendations() {
    return [
      {
        'id': '1',
        'type': 'warning',
        'icon': 'account_balance',
        'title': 'Loan Repayment Due in 3 Days',
        'message':
            'Your vehicle loan repayment of TSh 2,500,000 is due on July 29. Ensure funds are available.',
        'action': 'Create Repayment Task',
        'category': 'loan',
        'priority': 'high',
      },
      {
        'id': '2',
        'type': 'alert',
        'icon': 'directions_car',
        'title': 'Vehicle Insurance Expires Next Week',
        'message':
            'Your fleet insurance expires in 7 days. Schedule renewal to avoid coverage gaps.',
        'action': 'Set Reminder',
        'category': 'asset',
        'priority': 'high',
      },
      {
        'id': '3',
        'type': 'insight',
        'icon': 'local_gas_station',
        'title': 'Fuel Expenses Increased by 18%',
        'message':
            'Fuel costs rose 18% this month compared to last month. Consider route optimization.',
        'action': 'View Analysis',
        'category': 'finance',
        'priority': 'medium',
      },
      {
        'id': '4',
        'type': 'suggestion',
        'icon': 'savings',
        'title': 'Emergency Fund Below Recommended Level',
        'message':
            'Your emergency fund covers only 2.5 months of expenses. Recommended minimum is 6 months.',
        'action': 'Create Savings Plan',
        'category': 'finance',
        'priority': 'medium',
      },
      {
        'id': '5',
        'type': 'opportunity',
        'icon': 'trending_up',
        'title': 'Investment Portfolio Not Reviewed',
        'message':
            'You have not reviewed your investments in 90 days. Market conditions have changed.',
        'action': 'Review Portfolio',
        'category': 'investment',
        'priority': 'normal',
      },
      {
        'id': '6',
        'type': 'success',
        'icon': 'emoji_events',
        'title': 'Monthly Savings Goal Reached!',
        'message':
            'Congratulations! You reached your TSh 10M emergency fund goal. Consider increasing investment contributions.',
        'action': 'Explore Investments',
        'category': 'goal',
        'priority': 'normal',
      },
    ];
  }

  List<Map<String, dynamic>> getSuggestedActions() {
    return [
      {
        'id': 'a1',
        'title': 'Schedule Vehicle Maintenance',
        'description': 'Bus #3 is due for service based on mileage tracking.',
        'icon': 'build',
        'requiresApproval': false,
        'category': 'asset',
      },
      {
        'id': 'a2',
        'title': 'Pay Loan Early',
        'description':
            'You have surplus cash. Paying TSh 500K extra reduces interest by TSh 120K.',
        'icon': 'payments',
        'requiresApproval': true,
        'category': 'loan',
      },
      {
        'id': 'a3',
        'title': 'Review Cash Flow',
        'description':
            'Monthly cash flow analysis is ready. Review to optimize spending.',
        'icon': 'waterfall_chart',
        'requiresApproval': false,
        'category': 'finance',
      },
      {
        'id': 'a4',
        'title': 'Create Investment Plan',
        'description':
            'Based on your savings goal achievement, create a new investment strategy.',
        'icon': 'account_balance_wallet',
        'requiresApproval': true,
        'category': 'investment',
      },
      {
        'id': 'a5',
        'title': 'Generate Executive Report',
        'description':
            'Monthly executive report for July 2026 is ready to be generated.',
        'icon': 'summarize',
        'requiresApproval': false,
        'category': 'report',
      },
    ];
  }

  // ─── DEMO DATA FALLBACKS ──────────────────────────────────────────────────

  List<Map<String, dynamic>> _demoNotifications() {
    return [
      {
        'id': 'n1',
        'title': 'Loan Repayment Due in 3 Days',
        'message':
            'Your vehicle loan repayment of TSh 2,500,000 is due on July 29, 2026.',
        'notification_type': 'loan',
        'priority': 'high',
        'status': 'unread',
        'created_at': DateTime.now()
            .subtract(const Duration(hours: 2))
            .toIso8601String(),
      },
      {
        'id': 'n2',
        'title': 'Business Revenue Alert',
        'message': 'Transport Co revenue dropped by 22% this month.',
        'notification_type': 'business',
        'priority': 'high',
        'status': 'unread',
        'created_at': DateTime.now()
            .subtract(const Duration(hours: 5))
            .toIso8601String(),
      },
      {
        'id': 'n3',
        'title': 'Savings Goal Achieved!',
        'message': 'You reached your Emergency Fund goal of TSh 10,000,000.',
        'notification_type': 'ai',
        'priority': 'normal',
        'status': 'unread',
        'created_at': DateTime.now()
            .subtract(const Duration(hours: 8))
            .toIso8601String(),
      },
      {
        'id': 'n4',
        'title': 'Vehicle Insurance Expiring Soon',
        'message': 'Your vehicle insurance expires in 7 days.',
        'notification_type': 'asset',
        'priority': 'high',
        'status': 'unread',
        'created_at': DateTime.now()
            .subtract(const Duration(days: 1))
            .toIso8601String(),
      },
      {
        'id': 'n5',
        'title': 'Investment Review Overdue',
        'message':
            'You have not reviewed your investment portfolio in 90 days.',
        'notification_type': 'investment',
        'priority': 'normal',
        'status': 'read',
        'created_at': DateTime.now()
            .subtract(const Duration(days: 2))
            .toIso8601String(),
      },
      {
        'id': 'n6',
        'title': 'Monthly Budget Exceeded',
        'message': 'Fuel expenses increased by 18% this month.',
        'notification_type': 'finance',
        'priority': 'normal',
        'status': 'read',
        'created_at': DateTime.now()
            .subtract(const Duration(days: 3))
            .toIso8601String(),
      },
    ];
  }

  List<Map<String, dynamic>> _demoReminders() {
    return [
      {
        'id': 'r1',
        'title': 'Renew Vehicle Insurance',
        'description': 'Contact insurance provider to renew fleet coverage.',
        'due_date': DateTime.now()
            .add(const Duration(days: 7))
            .toIso8601String(),
        'repeat_pattern': 'yearly',
        'completed': false,
      },
      {
        'id': 'r2',
        'title': 'Monthly Loan Repayment',
        'description': 'Transfer TSh 2,500,000 for vehicle loan repayment.',
        'due_date': DateTime.now()
            .add(const Duration(days: 3))
            .toIso8601String(),
        'repeat_pattern': 'monthly',
        'completed': false,
      },
      {
        'id': 'r3',
        'title': 'Quarterly Investment Review',
        'description': 'Review investment portfolio performance and rebalance.',
        'due_date': DateTime.now()
            .add(const Duration(days: 14))
            .toIso8601String(),
        'repeat_pattern': 'quarterly',
        'completed': false,
      },
    ];
  }

  List<Map<String, dynamic>> _demoTasks() {
    return [
      {
        'id': 't1',
        'title': 'Review Monthly Expenses',
        'description': 'Analyze spending patterns for July 2026.',
        'task_type': 'finance',
        'priority': 'medium',
        'status': 'pending',
        'due_date': DateTime.now()
            .add(const Duration(days: 1))
            .toIso8601String(),
      },
      {
        'id': 't2',
        'title': 'Renew Fleet Insurance',
        'description': 'Contact insurance provider and renew coverage.',
        'task_type': 'asset',
        'priority': 'high',
        'status': 'pending',
        'due_date': DateTime.now()
            .add(const Duration(days: 7))
            .toIso8601String(),
      },
      {
        'id': 't3',
        'title': 'Generate Annual Report',
        'description': 'Compile comprehensive annual financial report.',
        'task_type': 'report',
        'priority': 'low',
        'status': 'pending',
        'due_date': DateTime.now()
            .add(const Duration(days: 30))
            .toIso8601String(),
      },
      {
        'id': 't4',
        'title': 'Loan Repayment - Vehicle Loan',
        'description': 'Process TSh 2,500,000 repayment before due date.',
        'task_type': 'loan',
        'priority': 'high',
        'status': 'pending',
        'due_date': DateTime.now()
            .add(const Duration(days: 3))
            .toIso8601String(),
      },
      {
        'id': 't5',
        'title': 'Business Revenue Review',
        'description': 'Executive review for Transport Co revenue decline.',
        'task_type': 'business',
        'priority': 'high',
        'status': 'completed',
        'due_date': DateTime.now()
            .subtract(const Duration(days: 2))
            .toIso8601String(),
      },
    ];
  }

  List<Map<String, dynamic>> _demoWorkflows() {
    return [
      {
        'id': 'w1',
        'name': 'Loan Due Alert',
        'trigger_type': 'loan_due',
        'condition': {'days_before': 3},
        'action': {'notify_user': true, 'create_task': true, 'ask_ai': true},
        'enabled': true,
        'created_at': DateTime.now()
            .subtract(const Duration(days: 30))
            .toIso8601String(),
      },
      {
        'id': 'w2',
        'name': 'Business Revenue Drop Alert',
        'trigger_type': 'revenue_drop',
        'condition': {'threshold_percent': 20},
        'action': {
          'generate_report': true,
          'notify_owner': true,
          'create_review_task': true,
        },
        'enabled': true,
        'created_at': DateTime.now()
            .subtract(const Duration(days: 25))
            .toIso8601String(),
      },
      {
        'id': 'w3',
        'name': 'Savings Goal Reached',
        'trigger_type': 'goal_achieved',
        'condition': {'goal_type': 'savings'},
        'action': {'congratulate': true, 'suggest_investment': true},
        'enabled': true,
        'created_at': DateTime.now()
            .subtract(const Duration(days: 20))
            .toIso8601String(),
      },
    ];
  }

  List<Map<String, dynamic>> _demoEvents() {
    return [
      {
        'id': 'e1',
        'event_type': 'loan_due',
        'entity_type': 'loan',
        'payload': {
          'loan_name': 'Vehicle Loan',
          'days_remaining': 3,
          'amount': 2500000,
        },
        'processed': false,
        'created_at': DateTime.now()
            .subtract(const Duration(hours: 1))
            .toIso8601String(),
      },
    ];
  }

  List<Map<String, dynamic>> _demoWorkflowLogs() {
    return [
      {
        'id': 'l1',
        'workflow_id': 'w1',
        'status': 'completed',
        'execution_time': DateTime.now()
            .subtract(const Duration(hours: 1))
            .toIso8601String(),
        'result': {
          'actions_executed': 3,
          'notification_sent': true,
          'task_created': true,
        },
      },
      {
        'id': 'l2',
        'workflow_id': 'w3',
        'status': 'completed',
        'execution_time': DateTime.now()
            .subtract(const Duration(hours: 2))
            .toIso8601String(),
        'result': {'actions_executed': 2, 'notification_sent': true},
      },
    ];
  }
}