import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// CNA Language Provider — persists language preference and notifies all listeners
class LanguageProvider extends ChangeNotifier {
  static const String _key = 'app_language';

  String _language = 'English';
  String get language => _language;

  Locale get locale {
    switch (_language) {
      case 'Swahili':
        return const Locale('sw', 'TZ');
      case 'French':
        return const Locale('fr', 'FR');
      case 'Arabic':
        return const Locale('ar', 'SA');
      default:
        return const Locale('en', 'US');
    }
  }

  LanguageProvider() {
    _load();
  }

  Future<void> _load() async {
    final prefs = await SharedPreferences.getInstance();
    _language = prefs.getString(_key) ?? 'English';
    notifyListeners();
  }

  Future<void> setLanguage(String lang) async {
    _language = lang;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, lang);
  }

  static const List<String> supportedLanguages = [
    'English',
    'Swahili',
    'French',
    'Arabic',
  ];

  /// Returns translated string for a given key.
  /// Falls back to English if translation is missing.
  String t(String key) {
    final map = _translations[_language];
    if (map == null) return _translations['English']?[key] ?? key;
    return map[key] ?? _translations['English']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'English': {
      'dashboard': 'Dashboard',
      'profile': 'Profile',
      'settings': 'Settings',
      'security': 'Security',
      'logout': 'Sign Out',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'confirm': 'Confirm',
      'yes': 'Yes',
      'no': 'No',
      'back': 'Back',
      'next': 'Next',
      'done': 'Done',
      'close': 'Close',
      'name': 'Full Name',
      'email': 'Email',
      'phone': 'Phone',
      'country': 'Country',
      'city': 'City',
      'address': 'Address',
      'language': 'Language',
      'theme': 'Theme',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'currency': 'Currency',
      'timezone': 'Time Zone',
      'personal_info': 'Personal Information',
      'account_info': 'Account Information',
      'security_settings': 'Security Settings',
      'preferences': 'Preferences',
      'about': 'About',
      'terms': 'Terms of Service',
      'privacy': 'Privacy Policy',
      'support': 'Support',
      'version': 'Version',
      'biometric': 'Biometric Login',
      'two_factor': 'Two-Factor Auth',
      'change_password': 'Change Password',
      'pin_management': 'PIN Management',
      'delete_account': 'Delete Account',
      'export_data': 'Export Data',
      'finance': 'Finance',
      'assets': 'Assets',
      'investments': 'Investments',
      'loans': 'Loans',
      'business': 'Business',
      'ai_center': 'AI Center',
      'analytics': 'Analytics',
      'reports': 'Reports',
      'automation': 'Automation',
      'net_worth': 'Net Worth',
      'transactions': 'Transactions',
      'budget': 'Budget',
      'goals': 'Goals',
    },
    'Swahili': {
      'dashboard': 'Dashibodi',
      'profile': 'Wasifu',
      'settings': 'Mipangilio',
      'security': 'Usalama',
      'logout': 'Toka',
      'save': 'Hifadhi',
      'cancel': 'Ghairi',
      'delete': 'Futa',
      'edit': 'Hariri',
      'add': 'Ongeza',
      'search': 'Tafuta',
      'loading': 'Inapakia...',
      'error': 'Hitilafu',
      'success': 'Mafanikio',
      'confirm': 'Thibitisha',
      'yes': 'Ndiyo',
      'no': 'Hapana',
      'back': 'Rudi',
      'next': 'Ifuatayo',
      'done': 'Imekamilika',
      'close': 'Funga',
      'name': 'Jina Kamili',
      'email': 'Barua Pepe',
      'phone': 'Simu',
      'country': 'Nchi',
      'city': 'Mji',
      'address': 'Anwani',
      'language': 'Lugha',
      'theme': 'Mandhari',
      'dark_mode': 'Hali ya Giza',
      'notifications': 'Arifa',
      'currency': 'Sarafu',
      'timezone': 'Saa za Eneo',
      'personal_info': 'Taarifa za Kibinafsi',
      'account_info': 'Taarifa za Akaunti',
      'security_settings': 'Mipangilio ya Usalama',
      'preferences': 'Mapendeleo',
      'about': 'Kuhusu',
      'terms': 'Masharti ya Huduma',
      'privacy': 'Sera ya Faragha',
      'support': 'Msaada',
      'version': 'Toleo',
      'biometric': 'Kuingia kwa Biometriki',
      'two_factor': 'Uthibitishaji wa Hatua Mbili',
      'change_password': 'Badilisha Nywila',
      'pin_management': 'Usimamizi wa PIN',
      'delete_account': 'Futa Akaunti',
      'export_data': 'Hamisha Data',
      'finance': 'Fedha',
      'assets': 'Mali',
      'investments': 'Uwekezaji',
      'loans': 'Mikopo',
      'business': 'Biashara',
      'ai_center': 'Kituo cha AI',
      'analytics': 'Uchambuzi',
      'reports': 'Ripoti',
      'automation': 'Otomatiki',
      'net_worth': 'Thamani Halisi',
      'transactions': 'Miamala',
      'budget': 'Bajeti',
      'goals': 'Malengo',
    },
    'French': {
      'dashboard': 'Tableau de bord',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'security': 'Sécurité',
      'logout': 'Se déconnecter',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'add': 'Ajouter',
      'search': 'Rechercher',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'confirm': 'Confirmer',
      'yes': 'Oui',
      'no': 'Non',
      'back': 'Retour',
      'next': 'Suivant',
      'done': 'Terminé',
      'close': 'Fermer',
      'name': 'Nom complet',
      'email': 'E-mail',
      'phone': 'Téléphone',
      'country': 'Pays',
      'city': 'Ville',
      'address': 'Adresse',
      'language': 'Langue',
      'theme': 'Thème',
      'dark_mode': 'Mode sombre',
      'notifications': 'Notifications',
      'currency': 'Devise',
      'timezone': 'Fuseau horaire',
      'personal_info': 'Informations personnelles',
      'account_info': 'Informations du compte',
      'security_settings': 'Paramètres de sécurité',
      'preferences': 'Préférences',
      'about': 'À propos',
      'terms': 'Conditions d\'utilisation',
      'privacy': 'Politique de confidentialité',
      'support': 'Assistance',
      'version': 'Version',
      'biometric': 'Connexion biométrique',
      'two_factor': 'Authentification à deux facteurs',
      'change_password': 'Changer le mot de passe',
      'pin_management': 'Gestion du PIN',
      'delete_account': 'Supprimer le compte',
      'export_data': 'Exporter les données',
      'finance': 'Finance',
      'assets': 'Actifs',
      'investments': 'Investissements',
      'loans': 'Prêts',
      'business': 'Entreprise',
      'ai_center': 'Centre IA',
      'analytics': 'Analytique',
      'reports': 'Rapports',
      'automation': 'Automatisation',
      'net_worth': 'Valeur nette',
      'transactions': 'Transactions',
      'budget': 'Budget',
      'goals': 'Objectifs',
    },
    'Arabic': {
      'dashboard': 'لوحة التحكم',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'security': 'الأمان',
      'logout': 'تسجيل الخروج',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'add': 'إضافة',
      'search': 'بحث',
      'loading': 'جار التحميل...',
      'error': 'خطأ',
      'success': 'نجاح',
      'confirm': 'تأكيد',
      'yes': 'نعم',
      'no': 'لا',
      'back': 'رجوع',
      'next': 'التالي',
      'done': 'تم',
      'close': 'إغلاق',
      'name': 'الاسم الكامل',
      'email': 'البريد الإلكتروني',
      'phone': 'الهاتف',
      'country': 'البلد',
      'city': 'المدينة',
      'address': 'العنوان',
      'language': 'اللغة',
      'theme': 'المظهر',
      'dark_mode': 'الوضع الداكن',
      'notifications': 'الإشعارات',
      'currency': 'العملة',
      'timezone': 'المنطقة الزمنية',
      'personal_info': 'المعلومات الشخصية',
      'account_info': 'معلومات الحساب',
      'security_settings': 'إعدادات الأمان',
      'preferences': 'التفضيلات',
      'about': 'حول',
      'terms': 'شروط الخدمة',
      'privacy': 'سياسة الخصوصية',
      'support': 'الدعم',
      'version': 'الإصدار',
      'biometric': 'تسجيل الدخول البيومتري',
      'two_factor': 'المصادقة الثنائية',
      'change_password': 'تغيير كلمة المرور',
      'pin_management': 'إدارة رمز PIN',
      'delete_account': 'حذف الحساب',
      'export_data': 'تصدير البيانات',
      'finance': 'المالية',
      'assets': 'الأصول',
      'investments': 'الاستثمارات',
      'loans': 'القروض',
      'business': 'الأعمال',
      'ai_center': 'مركز الذكاء الاصطناعي',
      'analytics': 'التحليلات',
      'reports': 'التقارير',
      'automation': 'الأتمتة',
      'net_worth': 'صافي الثروة',
      'transactions': 'المعاملات',
      'budget': 'الميزانية',
      'goals': 'الأهداف',
    },
  };
}
